easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Deal
       - App\Entity\Stage
       - App\Entity\Task
       - App\Entity\Contact
       - App\Entity\Manager
       - App\Entity\Department
